//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditorBase.PluginRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditorBaseRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorBaseRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditorBase.PluginRes.EditorBaseRes", typeof(EditorBaseRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new Material Resource based on the Texture..
        /// </summary>
        public static string ActionDesc_CreateMaterial {
            get {
                return ResourceManager.GetString("ActionDesc_CreateMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new ShaderProgram Resource based on Vertex- and Fragmentshaders..
        /// </summary>
        public static string ActionDesc_CreateShaderProgram {
            get {
                return ResourceManager.GetString("ActionDesc_CreateShaderProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new Sound Resource based on the AudioData..
        /// </summary>
        public static string ActionDesc_CreateSound {
            get {
                return ResourceManager.GetString("ActionDesc_CreateSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new Texture Resource based on the Pixmap..
        /// </summary>
        public static string ActionDesc_CreateTexture {
            get {
                return ResourceManager.GetString("ActionDesc_CreateTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Camera on GameObject..
        /// </summary>
        public static string ActionDesc_FocusGameObject {
            get {
                return ResourceManager.GetString("ActionDesc_FocusGameObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a GameObject by instantiating the Prefab..
        /// </summary>
        public static string ActionDesc_InstantiatePrefab {
            get {
                return ResourceManager.GetString("ActionDesc_InstantiatePrefab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Resource in external editor..
        /// </summary>
        public static string ActionDesc_OpenResourceExternal {
            get {
                return ResourceManager.GetString("ActionDesc_OpenResourceExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Scene..
        /// </summary>
        public static string ActionDesc_OpenScene {
            get {
                return ResourceManager.GetString("ActionDesc_OpenScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Material.
        /// </summary>
        public static string ActionName_CreateMaterial {
            get {
                return ResourceManager.GetString("ActionName_CreateMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ShaderProgram.
        /// </summary>
        public static string ActionName_CreateShaderProgram {
            get {
                return ResourceManager.GetString("ActionName_CreateShaderProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sound.
        /// </summary>
        public static string ActionName_CreateSound {
            get {
                return ResourceManager.GetString("ActionName_CreateSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Texture.
        /// </summary>
        public static string ActionName_CreateTexture {
            get {
                return ResourceManager.GetString("ActionName_CreateTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string CamView_Action_Move {
            get {
                return ResourceManager.GetString("CamView_Action_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string CamView_Action_Rotate {
            get {
                return ResourceManager.GetString("CamView_Action_Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string CamView_Action_Scale {
            get {
                return ResourceManager.GetString("CamView_Action_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting....
        /// </summary>
        public static string CamView_Action_Select_Active {
            get {
                return ResourceManager.GetString("CamView_Action_Select_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Control Shortcuts.
        /// </summary>
        public static string CamView_Help_CamActions {
            get {
                return ResourceManager.GetString("CamView_Help_CamActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press F to focus the world origin..
        /// </summary>
        public static string CamView_Help_CamActions_Focus {
            get {
                return ResourceManager.GetString("CamView_Help_CamActions_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Mouse Wheel and Right Mouse button to move..
        /// </summary>
        public static string CamView_Help_CamActions_Move {
            get {
                return ResourceManager.GetString("CamView_Help_CamActions_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Space for alternative camera movement..
        /// </summary>
        public static string CamView_Help_CamActions_MoveAlternate {
            get {
                return ResourceManager.GetString("CamView_Help_CamActions_MoveAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Ctrl + Arrow Keys, Add or Subtract to move by a fixed step..
        /// </summary>
        public static string CamView_Help_CamActions_MoveStep {
            get {
                return ResourceManager.GetString("CamView_Help_CamActions_MoveStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Action Shortcuts.
        /// </summary>
        public static string CamView_Help_ObjActions {
            get {
                return ResourceManager.GetString("CamView_Help_ObjActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Shift to limit an action to one axis..
        /// </summary>
        public static string CamView_Help_ObjActions_AxisLock {
            get {
                return ResourceManager.GetString("CamView_Help_ObjActions_AxisLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Ctrl + C to clone the selected objects..
        /// </summary>
        public static string CamView_Help_ObjActions_Clone {
            get {
                return ResourceManager.GetString("CamView_Help_ObjActions_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Delete to remove the selected objects..
        /// </summary>
        public static string CamView_Help_ObjActions_Delete {
            get {
                return ResourceManager.GetString("CamView_Help_ObjActions_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Alt to perform an action on a clone of the current selection..
        /// </summary>
        public static string CamView_Help_ObjActions_EditClone {
            get {
                return ResourceManager.GetString("CamView_Help_ObjActions_EditClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press F to focus on the current selection..
        /// </summary>
        public static string CamView_Help_ObjActions_Focus {
            get {
                return ResourceManager.GetString("CamView_Help_ObjActions_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Arrow Keys, Add or Subtract to move the selected objects by a fixed step..
        /// </summary>
        public static string CamView_Help_ObjActions_MoveStep {
            get {
                return ResourceManager.GetString("CamView_Help_ObjActions_MoveStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle: {0:F}°.
        /// </summary>
        public static string CamView_Status_Angle {
            get {
                return ResourceManager.GetString("CamView_Status_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X: {0:F}.
        /// </summary>
        public static string CamView_Status_PosX {
            get {
                return ResourceManager.GetString("CamView_Status_PosX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y: {0:F}.
        /// </summary>
        public static string CamView_Status_PosY {
            get {
                return ResourceManager.GetString("CamView_Status_PosY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z: {0:F}.
        /// </summary>
        public static string CamView_Status_PosZ {
            get {
                return ResourceManager.GetString("CamView_Status_PosZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fades out the actual scene rendering to improve Layer visibility.
        /// </summary>
        public static string CamViewLayer_BackPlate_Desc {
            get {
                return ResourceManager.GetString("CamViewLayer_BackPlate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Plate.
        /// </summary>
        public static string CamViewLayer_BackPlate_Name {
            get {
                return ResourceManager.GetString("CamViewLayer_BackPlate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a uniform spatial grid.
        /// </summary>
        public static string CamViewLayer_Grid_Desc {
            get {
                return ResourceManager.GetString("CamViewLayer_Grid_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string CamViewLayer_Grid_Name {
            get {
                return ResourceManager.GetString("CamViewLayer_Grid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the physical constraints of a RigidBody Component.
        /// </summary>
        public static string CamViewLayer_RigidBodyJoint_Desc {
            get {
                return ResourceManager.GetString("CamViewLayer_RigidBodyJoint_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RigidBody Joints.
        /// </summary>
        public static string CamViewLayer_RigidBodyJoint_Name {
            get {
                return ResourceManager.GetString("CamViewLayer_RigidBodyJoint_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the physical shape of a RigidBody Component.
        /// </summary>
        public static string CamViewLayer_RigidBodyShape_Desc {
            get {
                return ResourceManager.GetString("CamViewLayer_RigidBodyShape_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RigidBody Shapes.
        /// </summary>
        public static string CamViewLayer_RigidBodyShape_Name {
            get {
                return ResourceManager.GetString("CamViewLayer_RigidBodyShape_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game View.
        /// </summary>
        public static string CamViewState_GameView_Name {
            get {
                return ResourceManager.GetString("CamViewState_GameView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RigidBody Editor.
        /// </summary>
        public static string CamViewState_RigidBodyEditor_Name {
            get {
                return ResourceManager.GetString("CamViewState_RigidBodyEditor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene Editor.
        /// </summary>
        public static string CamViewState_SceneEditor_Name {
            get {
                return ResourceManager.GetString("CamViewState_SceneEditor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Circle....
        /// </summary>
        public static string ColliderEditor_CreateCircle {
            get {
                return ResourceManager.GetString("ColliderEditor_CreateCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Loop....
        /// </summary>
        public static string ColliderEditor_CreateLoop {
            get {
                return ResourceManager.GetString("ColliderEditor_CreateLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Polygon....
        /// </summary>
        public static string ColliderEditor_CreatePolygon {
            get {
                return ResourceManager.GetString("ColliderEditor_CreatePolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CursorArrowCreateCircle {
            get {
                object obj = ResourceManager.GetObject("CursorArrowCreateCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CursorArrowCreateEdge {
            get {
                object obj = ResourceManager.GetObject("CursorArrowCreateEdge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CursorArrowCreateLoop {
            get {
                object obj = ResourceManager.GetObject("CursorArrowCreateLoop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CursorArrowCreatePolygon {
            get {
                object obj = ResourceManager.GetObject("CursorArrowCreatePolygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DropdownSettingsBlack {
            get {
                object obj = ResourceManager.GetObject("DropdownSettingsBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconAbortCross {
            get {
                object obj = ResourceManager.GetObject("IconAbortCross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCmpCamera {
            get {
                object obj = ResourceManager.GetObject("IconCmpCamera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCmpCapsuleCollider {
            get {
                object obj = ResourceManager.GetObject("IconCmpCapsuleCollider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCmpCircleCollider {
            get {
                object obj = ResourceManager.GetObject("IconCmpCircleCollider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCmpEdgeCollider {
            get {
                object obj = ResourceManager.GetObject("IconCmpEdgeCollider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCmpLoopCollider {
            get {
                object obj = ResourceManager.GetObject("IconCmpLoopCollider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCmpProfileRenderer {
            get {
                object obj = ResourceManager.GetObject("IconCmpProfileRenderer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCmpRectCollider {
            get {
                object obj = ResourceManager.GetObject("IconCmpRectCollider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCmpRigidBodyRenderer {
            get {
                object obj = ResourceManager.GetObject("IconCmpRigidBodyRenderer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCmpSoundListener {
            get {
                object obj = ResourceManager.GetObject("IconCmpSoundListener", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCmpSpriteRenderer {
            get {
                object obj = ResourceManager.GetObject("IconCmpSpriteRenderer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCmpTransform {
            get {
                object obj = ResourceManager.GetObject("IconCmpTransform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCmpUnknown {
            get {
                object obj = ResourceManager.GetObject("IconCmpUnknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconDatabase {
            get {
                object obj = ResourceManager.GetObject("IconDatabase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon IconEye {
            get {
                object obj = ResourceManager.GetObject("IconEye", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconEyeCross {
            get {
                object obj = ResourceManager.GetObject("IconEyeCross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconGameObj {
            get {
                object obj = ResourceManager.GetObject("IconGameObj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconLock {
            get {
                object obj = ResourceManager.GetObject("IconLock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconLogCore {
            get {
                object obj = ResourceManager.GetObject("IconLogCore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconLogEditor {
            get {
                object obj = ResourceManager.GetObject("IconLogEditor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconLogError {
            get {
                object obj = ResourceManager.GetObject("IconLogError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconLogGame {
            get {
                object obj = ResourceManager.GetObject("IconLogGame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconLogMessage {
            get {
                object obj = ResourceManager.GetObject("IconLogMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon IconLogView {
            get {
                object obj = ResourceManager.GetObject("IconLogView", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconLogWarning {
            get {
                object obj = ResourceManager.GetObject("IconLogWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon IconObjView {
            get {
                object obj = ResourceManager.GetObject("IconObjView", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon IconProjectView {
            get {
                object obj = ResourceManager.GetObject("IconProjectView", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconResAudioData {
            get {
                object obj = ResourceManager.GetObject("IconResAudioData", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconResDrawTechnique {
            get {
                object obj = ResourceManager.GetObject("IconResDrawTechnique", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconResFont {
            get {
                object obj = ResourceManager.GetObject("IconResFont", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconResFragmentShader {
            get {
                object obj = ResourceManager.GetObject("IconResFragmentShader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconResMaterial {
            get {
                object obj = ResourceManager.GetObject("IconResMaterial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconResPixmap {
            get {
                object obj = ResourceManager.GetObject("IconResPixmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconResPrefabEmpty {
            get {
                object obj = ResourceManager.GetObject("IconResPrefabEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconResPrefabFull {
            get {
                object obj = ResourceManager.GetObject("IconResPrefabFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconResRenderTarget {
            get {
                object obj = ResourceManager.GetObject("IconResRenderTarget", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconResScene {
            get {
                object obj = ResourceManager.GetObject("IconResScene", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconResShaderProgram {
            get {
                object obj = ResourceManager.GetObject("IconResShaderProgram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconResSound {
            get {
                object obj = ResourceManager.GetObject("IconResSound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconResTexture {
            get {
                object obj = ResourceManager.GetObject("IconResTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconResUnknown {
            get {
                object obj = ResourceManager.GetObject("IconResUnknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconResVertexShader {
            get {
                object obj = ResourceManager.GetObject("IconResVertexShader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon IconSceneView {
            get {
                object obj = ResourceManager.GetObject("IconSceneView", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconSpeakerBlack {
            get {
                object obj = ResourceManager.GetObject("IconSpeakerBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconSpeakerWhite {
            get {
                object obj = ResourceManager.GetObject("IconSpeakerWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy All.
        /// </summary>
        public static string LogView_ContextMenu_CopyAllItems {
            get {
                return ResourceManager.GetString("LogView_ContextMenu_CopyAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string LogView_ContextMenu_CopyItem {
            get {
                return ResourceManager.GetString("LogView_ContextMenu_CopyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Source.
        /// </summary>
        public static string LogView_ContextMenu_ShowSource {
            get {
                return ResourceManager.GetString("LogView_ContextMenu_ShowSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string LogView_Errors {
            get {
                return ResourceManager.GetString("LogView_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string LogView_Warnings {
            get {
                return ResourceManager.GetString("LogView_Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remove {0} because it is required by the &apos;{1}&apos; Component..
        /// </summary>
        public static string MenuItemDesc_CantRemoveComponent {
            get {
                return ResourceManager.GetString("MenuItemDesc_CantRemoveComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Data.
        /// </summary>
        public static string MenuItemName_AppData {
            get {
                return ResourceManager.GetString("MenuItemName_AppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string MenuItemName_CamView {
            get {
                return ResourceManager.GetString("MenuItemName_CamView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log View.
        /// </summary>
        public static string MenuItemName_LogView {
            get {
                return ResourceManager.GetString("MenuItemName_LogView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Inspector.
        /// </summary>
        public static string MenuItemName_ObjView {
            get {
                return ResourceManager.GetString("MenuItemName_ObjView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project View.
        /// </summary>
        public static string MenuItemName_ProjectView {
            get {
                return ResourceManager.GetString("MenuItemName_ProjectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string MenuItemName_RemoveComponent {
            get {
                return ResourceManager.GetString("MenuItemName_RemoveComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string MenuItemName_ResetComponent {
            get {
                return ResourceManager.GetString("MenuItemName_ResetComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Inspector.
        /// </summary>
        public static string MenuItemName_ResView {
            get {
                return ResourceManager.GetString("MenuItemName_ResView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene View.
        /// </summary>
        public static string MenuItemName_SceneView {
            get {
                return ResourceManager.GetString("MenuItemName_SceneView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default User Data.
        /// </summary>
        public static string MenuItemName_UserData {
            get {
                return ResourceManager.GetString("MenuItemName_UserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string NewFolderName {
            get {
                return ResourceManager.GetString("NewFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OverlayLink {
            get {
                object obj = ResourceManager.GetObject("OverlayLink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OverlayLinkBroken {
            get {
                object obj = ResourceManager.GetObject("OverlayLinkBroken", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubleclick: {0}.
        /// </summary>
        public static string ProjectFolderView_Help_Doubleclick {
            get {
                return ResourceManager.GetString("ProjectFolderView_Help_Doubleclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t move file.
        /// </summary>
        public static string ProjectFolderView_MsgBox_CantMove_Caption {
            get {
                return ResourceManager.GetString("ProjectFolderView_MsgBox_CantMove_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t move file to &apos;{0}&apos; because it would overwrite an existing file..
        /// </summary>
        public static string ProjectFolderView_MsgBox_CantMove_Text {
            get {
                return ResourceManager.GetString("ProjectFolderView_MsgBox_CantMove_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t rename file.
        /// </summary>
        public static string ProjectFolderView_MsgBox_CantRename_Caption {
            get {
                return ResourceManager.GetString("ProjectFolderView_MsgBox_CantRename_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t rename file to &apos;{0}&apos; because it would overwrite an existing file..
        /// </summary>
        public static string ProjectFolderView_MsgBox_CantRename_Text {
            get {
                return ResourceManager.GetString("ProjectFolderView_MsgBox_CantRename_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected files?.
        /// </summary>
        public static string ProjectFolderView_MsgBox_ConfirmDeleteSelectedFiles_Caption {
            get {
                return ResourceManager.GetString("ProjectFolderView_MsgBox_ConfirmDeleteSelectedFiles_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the selected files?.
        /// </summary>
        public static string ProjectFolderView_MsgBox_ConfirmDeleteSelectedFiles_Text {
            get {
                return ResourceManager.GetString("ProjectFolderView_MsgBox_ConfirmDeleteSelectedFiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ProjectNameLabel {
            get {
                return ResourceManager.GetString("ProjectNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a joint type and click the add button to add a new joint to the Collider.
        /// </summary>
        public static string PropertyDesc_AddJoint {
            get {
                return ResourceManager.GetString("PropertyDesc_AddJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The joints second Collider, i.e. the one that is connected to this one using the joint..
        /// </summary>
        public static string PropertyDesc_OtherCollider {
            get {
                return ResourceManager.GetString("PropertyDesc_OtherCollider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Joint....
        /// </summary>
        public static string PropertyName_AddJoint {
            get {
                return ResourceManager.GetString("PropertyName_AddJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Collider.
        /// </summary>
        public static string PropertyName_OtherCollider {
            get {
                return ResourceManager.GetString("PropertyName_OtherCollider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RigidBody.
        /// </summary>
        public static string RigidBodyCamViewState_SelBodyName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelBodyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Shape.
        /// </summary>
        public static string RigidBodyCamViewState_SelCircleShapeName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelCircleShapeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Shape.
        /// </summary>
        public static string RigidBodyCamViewState_SelLoopShapeName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelLoopShapeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon Shape.
        /// </summary>
        public static string RigidBodyCamViewState_SelPolyShapeName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelPolyShapeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        public static string RigidBodyCamViewState_SelShapeName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelShapeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene.
        /// </summary>
        public static string SceneNameLabel {
            get {
                return ResourceManager.GetString("SceneNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Scene.
        /// </summary>
        public static string SceneNameNotYetSaved {
            get {
                return ResourceManager.GetString("SceneNameNotYetSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubleclick: {0}.
        /// </summary>
        public static string SceneView_Help_Doubleclick {
            get {
                return ResourceManager.GetString("SceneView_Help_Doubleclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string SceneView_Item_Hidden {
            get {
                return ResourceManager.GetString("SceneView_Item_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object is currently locked and hidden. Click to show and unlock..
        /// </summary>
        public static string SceneView_Item_Hidden_Tooltip {
            get {
                return ResourceManager.GetString("SceneView_Item_Hidden_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string SceneView_Item_Locked {
            get {
                return ResourceManager.GetString("SceneView_Item_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object is currently locked. Click to hide or unlock..
        /// </summary>
        public static string SceneView_Item_Locked_Tooltip {
            get {
                return ResourceManager.GetString("SceneView_Item_Locked_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock / Hide.
        /// </summary>
        public static string SceneView_Item_LockHide {
            get {
                return ResourceManager.GetString("SceneView_Item_LockHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to lock or hide the object while editing..
        /// </summary>
        public static string SceneView_Item_LockHide_Tooltip {
            get {
                return ResourceManager.GetString("SceneView_Item_LockHide_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked to: {0}.
        /// </summary>
        public static string SceneView_PrefabLink {
            get {
                return ResourceManager.GetString("SceneView_PrefabLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0}.
        /// </summary>
        public static string UndoRedo_CreateRigidBodyJoint {
            get {
                return ResourceManager.GetString("UndoRedo_CreateRigidBodyJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0} Joints.
        /// </summary>
        public static string UndoRedo_CreateRigidBodyJointMulti {
            get {
                return ResourceManager.GetString("UndoRedo_CreateRigidBodyJointMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0}.
        /// </summary>
        public static string UndoRedo_CreateRigidBodyShape {
            get {
                return ResourceManager.GetString("UndoRedo_CreateRigidBodyShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0} Shapes.
        /// </summary>
        public static string UndoRedo_CreateRigidBodyShapeMulti {
            get {
                return ResourceManager.GetString("UndoRedo_CreateRigidBodyShapeMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Source {0}.
        /// </summary>
        public static string UndoRedo_CreateSoundEmitterSource {
            get {
                return ResourceManager.GetString("UndoRedo_CreateSoundEmitterSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0} Sources.
        /// </summary>
        public static string UndoRedo_CreateSoundEmitterSourceMulti {
            get {
                return ResourceManager.GetString("UndoRedo_CreateSoundEmitterSourceMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} Objects.
        /// </summary>
        public static string UndoRedo_DeleteObjects {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string UndoRedo_DeleteRigidBodyJoint {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteRigidBodyJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} Joints.
        /// </summary>
        public static string UndoRedo_DeleteRigidBodyJointMulti {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteRigidBodyJointMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string UndoRedo_DeleteRigidBodyShape {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteRigidBodyShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} Shapes.
        /// </summary>
        public static string UndoRedo_DeleteRigidBodyShapeMulti {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteRigidBodyShapeMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Source {0}.
        /// </summary>
        public static string UndoRedo_DeleteSoundEmitterSource {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteSoundEmitterSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} Sources.
        /// </summary>
        public static string UndoRedo_DeleteSoundEmitterSourceMulti {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteSoundEmitterSourceMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop {0}.
        /// </summary>
        public static string UndoRedo_DropGameObjectInScene {
            get {
                return ResourceManager.GetString("UndoRedo_DropGameObjectInScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop {0} GameObjects.
        /// </summary>
        public static string UndoRedo_DropGameObjectInSceneMulti {
            get {
                return ResourceManager.GetString("UndoRedo_DropGameObjectInSceneMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {0}.
        /// </summary>
        public static string UndoRedo_MoveCamViewObj {
            get {
                return ResourceManager.GetString("UndoRedo_MoveCamViewObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {0} Objects.
        /// </summary>
        public static string UndoRedo_MoveCamViewObjMulti {
            get {
                return ResourceManager.GetString("UndoRedo_MoveCamViewObjMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reparent {0}.
        /// </summary>
        public static string UndoRedo_ReparentRigidBodyJoint {
            get {
                return ResourceManager.GetString("UndoRedo_ReparentRigidBodyJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reparent {0} Joints.
        /// </summary>
        public static string UndoRedo_ReparentRigidBodyJointMulti {
            get {
                return ResourceManager.GetString("UndoRedo_ReparentRigidBodyJointMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate {0}.
        /// </summary>
        public static string UndoRedo_RotateCamViewObj {
            get {
                return ResourceManager.GetString("UndoRedo_RotateCamViewObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate {0} Objects.
        /// </summary>
        public static string UndoRedo_RotateCamViewObjMulti {
            get {
                return ResourceManager.GetString("UndoRedo_RotateCamViewObjMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale {0}.
        /// </summary>
        public static string UndoRedo_ScaleCamViewObj {
            get {
                return ResourceManager.GetString("UndoRedo_ScaleCamViewObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale {0} Objects.
        /// </summary>
        public static string UndoRedo_ScaleCamViewObjMulti {
            get {
                return ResourceManager.GetString("UndoRedo_ScaleCamViewObjMulti", resourceCulture);
            }
        }
    }
}
